// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxAJ4TVD_8xEKOFfcztwt-0k-gWVqRCVg',
    appId: '1:478554081074:web:a1e32436568d48a1caf92b',
    messagingSenderId: '478554081074',
    projectId: 'personify-f6666',
    authDomain: 'personify-f6666.firebaseapp.com',
    storageBucket: 'personify-f6666.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nk8FM0y09ArVMJyjeqkF9NYZuwhZIPA',
    appId: '1:478554081074:android:3ddb9b186b20f884caf92b',
    messagingSenderId: '478554081074',
    projectId: 'personify-f6666',
    storageBucket: 'personify-f6666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZcLY90r3tgQxjc0SE9NBUz-aq93Yi320',
    appId: '1:478554081074:ios:c5745060e7cf777acaf92b',
    messagingSenderId: '478554081074',
    projectId: 'personify-f6666',
    storageBucket: 'personify-f6666.appspot.com',
    iosBundleId: 'com.example.personifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZcLY90r3tgQxjc0SE9NBUz-aq93Yi320',
    appId: '1:478554081074:ios:0d3b24287dc1583ccaf92b',
    messagingSenderId: '478554081074',
    projectId: 'personify-f6666',
    storageBucket: 'personify-f6666.appspot.com',
    iosBundleId: 'com.example.personifyApp.RunnerTests',
  );
}
